"""Centralized image cache management.

Organized directory structure:
  output/visuals/
    personas/          → {codename}.png (permanent, one per agent)
    backgrounds/       → bg_theme_{style_id}_{page_idx}.png (cached by theme)
    foregrounds/       → fg_{run_id}_{page_idx}.png (per-run, content-specific)
    covers/            → cover_{run_id}.png (per-run, content-specific)
    infographics/      → stats/bars/timeline per run
    manifest.json      → tracks all cached images with metadata

Cache strategy:
  - Personas: PERMANENT — generated once, reused forever (21 agents)
  - Backgrounds: THEME-CACHED — one set per style_id (12 styles × 5 pages = 60 max)
  - Foregrounds: RUN-SPECIFIC — content-aware, new each run (but reused in --sim mode)
  - Covers: RUN-SPECIFIC — content-specific, new each run (but reused in --sim mode)
  - Infographics: RUN-SPECIFIC — generated by Pillow per run
"""
import json
import os
import shutil
from pathlib import Path
from datetime import datetime

from aibrief import config

VISUALS_DIR = config.OUTPUT_DIR / "visuals"
MANIFEST_PATH = VISUALS_DIR / "manifest.json"

# Subdirectories
PERSONAS_DIR = VISUALS_DIR / "personas"
BACKGROUNDS_DIR = VISUALS_DIR / "backgrounds"
FOREGROUNDS_DIR = VISUALS_DIR / "foregrounds"
COVERS_DIR = VISUALS_DIR / "covers"
INFOGRAPHICS_DIR = VISUALS_DIR / "infographics"

# Create all directories
for d in [PERSONAS_DIR, BACKGROUNDS_DIR, FOREGROUNDS_DIR,
          COVERS_DIR, INFOGRAPHICS_DIR]:
    d.mkdir(parents=True, exist_ok=True)


def _load_manifest() -> dict:
    if MANIFEST_PATH.exists():
        try:
            return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        except Exception:
            return {}
    return {}


def _save_manifest(manifest: dict):
    MANIFEST_PATH.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def register_image(category: str, key: str, path: str, **metadata):
    """Register an image in the manifest."""
    manifest = _load_manifest()
    if category not in manifest:
        manifest[category] = {}
    manifest[category][key] = {
        "path": str(path),
        "size_kb": round(os.path.getsize(path) / 1024, 1)
        if os.path.exists(path) else 0,
        "created": datetime.now().isoformat(),
        **metadata,
    }
    _save_manifest(manifest)


def lookup_image(category: str, key: str) -> str:
    """Look up a cached image. Returns path if exists, empty string if not."""
    manifest = _load_manifest()
    entry = manifest.get(category, {}).get(key, {})
    path = entry.get("path", "")
    if path and os.path.exists(path):
        return path
    return ""


def get_cache_stats() -> dict:
    """Get summary statistics of the image cache."""
    manifest = _load_manifest()
    stats = {}
    for category, images in manifest.items():
        total_kb = 0
        count = 0
        for key, entry in images.items():
            if os.path.exists(entry.get("path", "")):
                count += 1
                total_kb += entry.get("size_kb", 0)
        stats[category] = {"count": count, "total_mb": round(total_kb / 1024, 1)}
    return stats


def migrate_legacy_images():
    """One-time migration: move old flat-directory images to organized subdirectories.

    Call once; safe to call multiple times (only moves files that exist in old location).
    """
    moved = 0
    old_dir = VISUALS_DIR
    manifest = _load_manifest()

    # Migrate personas (already in personas/ — just register them)
    for f in PERSONAS_DIR.glob("*.png"):
        key = f.stem  # e.g., "aria"
        if "personas" not in manifest:
            manifest["personas"] = {}
        if key not in manifest.get("personas", {}):
            manifest["personas"][key] = {
                "path": str(f),
                "size_kb": round(f.stat().st_size / 1024, 1),
                "created": datetime.now().isoformat(),
            }

    # Migrate theme backgrounds
    for f in old_dir.glob("bg_theme_*.png"):
        dest = BACKGROUNDS_DIR / f.name
        if not dest.exists():
            shutil.copy2(str(f), str(dest))
            moved += 1
        key = f.stem  # e.g., "bg_theme_anime_pop_1"
        if "backgrounds" not in manifest:
            manifest["backgrounds"] = {}
        manifest["backgrounds"][key] = {
            "path": str(dest),
            "size_kb": round(dest.stat().st_size / 1024, 1),
            "created": datetime.now().isoformat(),
        }

    # Migrate covers (keep originals for backward compat)
    for f in old_dir.glob("cover_*.png"):
        dest = COVERS_DIR / f.name
        if not dest.exists():
            shutil.copy2(str(f), str(dest))
            moved += 1
        key = f.stem
        if "covers" not in manifest:
            manifest["covers"] = {}
        manifest["covers"][key] = {
            "path": str(dest),
            "size_kb": round(dest.stat().st_size / 1024, 1),
            "created": datetime.now().isoformat(),
        }

    # Migrate foregrounds
    for f in old_dir.glob("fg_*.png"):
        dest = FOREGROUNDS_DIR / f.name
        if not dest.exists():
            shutil.copy2(str(f), str(dest))
            moved += 1
        key = f.stem
        if "foregrounds" not in manifest:
            manifest["foregrounds"] = {}
        manifest["foregrounds"][key] = {
            "path": str(dest),
            "size_kb": round(dest.stat().st_size / 1024, 1),
            "created": datetime.now().isoformat(),
        }

    _save_manifest(manifest)
    return moved


def persona_path(codename: str) -> str:
    """Get the cached persona image path."""
    return str(PERSONAS_DIR / f"{codename.lower()}.png")


def background_path(style_id: str, page_idx: int) -> str:
    """Get the cached background image path (theme-cached)."""
    return str(BACKGROUNDS_DIR / f"bg_theme_{style_id}_{page_idx}.png")


def foreground_path(run_id: str, page_idx: int) -> str:
    """Get the foreground image path (run-specific)."""
    return str(FOREGROUNDS_DIR / f"fg_{run_id}_{page_idx}.png")


def cover_path(run_id: str) -> str:
    """Get the cover image path (run-specific)."""
    return str(COVERS_DIR / f"cover_{run_id}.png")
